<?='<?xml version="1.0" encoding="UTF-8"?>'?>
<journal>
	<metadata>
	<?if(!empty(trim(preference('bas_organisation_name')))):?>
		<title><?=preference('bas_organisation_name')?></title>
	<?endif?>
	<?if(!empty($issue->publisher)):?>
		<publisher><?=$issue->publisher?></publisher>
	<?endif?>
	<?if(!empty(trim(preference('bas_issn')))):?>
		<issn><?=preference('bas_issn')?></issn>
	<?endif?>
		<doi><?=str_replace("http://dx.doi.org/", "", rtrim(preference('bas_doi_prefix'), '/'))?></doi>
	<?if(!empty(trim(preference('bas_copyright_statement')))):?>
		<copyright-statement><?=htmlspecialchars(preference('bas_copyright_statement'))?></copyright-statement>
	<?endif?>
	<?if(!empty(trim(preference('bas_publisher_statement')))):?>
		<publisher-statement><?=htmlspecialchars(preference('bas_publisher_statement'))?></publisher-statement>
	<?endif?>
	</metadata>
	<issue>
	<?if(!empty(trim($issue->title))):?>
		<title><?=$issue->title?></title>
	<?endif?>
	<?if(!empty(trim($issue->publish_date))):?>
		<date><?=$issue->publish_date?></date>
	<?endif?>
	<?if(!empty(trim($issue->issue_number))):?>
		<issue-number><?=$issue->issue_number?></issue-number>
	<?endif?>
		<doi><?=str_replace("http://dx.doi.org/", "", rtrim(preference('bas_doi_prefix'), '/'))?>/<?=$issue->doi?></doi>
	<?if(!empty(trim($issue->season))):?>
		<season><?=$issue->season?></season>
	<?endif?>
		<?if($issue->media!=null):?>
			<cover-image>
				<url>https://pmc.qi-cms.com/media/_source/<?=$issue->media->path?>/<?=$issue->media->filename?></url> 
				<title><?=htmlspecialchars($issue->media->title)?></title>
				<caption><?=htmlspecialchars($issue->media->caption)?></caption>
				<credits><?=htmlspecialchars($issue->media->credits)?></credits>
				<copyright><?=htmlspecialchars($issue->media->copyright)?></copyright>
			</cover-image>
		<?endif?>
		<?foreach($issue->authors as $author):?>
			<issue-editors>
			<?if(!empty(trim($author->forename))):?>
				<forename><?=$author->forename?></forename>
			<?endif?>
			<?if(!empty(trim($author->surname))):?>
				<surname><?=$author->surname?></surname>
			<?endif?>
			<?if(!empty(trim($author->occupation))):?>
				<occupation><?=$author->occupation?></occupation>
			<?endif?>
			<?if(!empty(trim($author->short_description))):?>
				<bio><?=htmlspecialchars($author->short_description)?></bio>
			<?endif?>
			<?if(!empty(trim($author->organisation))):?>
				<affiliation><?=$author->organisation?></affiliation>
			<?endif?>
			<?if(!empty(trim($author->orcid_id))):?>
				<orcid-id><?=$author->orcid_id?></orcid-id>
			<?endif?>
			</issue-editors>
		<?endforeach?>
		<?foreach($issue->articles as $article):?>
			<article>
			<?if(!empty(trim($article->rank))):?>
				<rank><?=$article->rank?></rank>
			<?endif?>
			<?if(!empty(trim($article->title))):?>
				<title><?=htmlspecialchars($article->title)?></title>
			<?endif?>
			<?if(!empty(trim($article->category))):?>
				<type><?=htmlspecialchars($article->category)?></type>
			<?endif?>
			<?if(!empty(trim($article->short_title))):?>
				<short-title><?=htmlspecialchars($article->short_title)?></short-title>
			<?endif?>	
				<?foreach($article->authors as $author):?>
					<author>
					<?if(!empty(trim($author->forename))):?>
						<forename><?=$author->forename?></forename>
					<?endif?>
					<?if(!empty(trim($author->surname))):?>
						<surname><?=$author->surname?></surname>
					<?endif?>
					<?if(!empty(trim($author->occupation))):?>
						<occupation><?=$author->occupation?></occupation>
					<?endif?>
					<?if(!empty(trim($author->short_description))):?>
						<bio><?=htmlspecialchars($author->short_description)?></bio>
					<?endif?>
					<?if(!empty(trim($author->organisation))):?>
						<affiliation><?=$author->organisation?></affiliation>
					<?endif?>
					<?if(!empty(trim($author->orcid_id))):?>
						<orcid-id><?=$author->orcid_id?></orcid-id>
					<?endif?>
					</author>
				<?endforeach?>
			<?if(!empty(trim($article->bas_review_status))):?>
				<review-status><?=$article->bas_review_status?></review-status>
			<?endif?>
			<?if(!empty(trim($article->bas_licence_status))):?>
				<licence><?=$article->bas_licence_status?></licence>
			<?endif?>
			<?if(!empty(trim($article->bas_licence_status_url))):?>
				<licence-url><?=$article->bas_licence_status_url?></licence-url>
			<?endif?>
				<doi><?=str_replace("http://dx.doi.org/", "", rtrim(preference('bas_doi_prefix'), '/'))?>/<?=$issue->doi?>/<?=$article->doi?></doi>
			<?if(!empty(trim($article->permanent_url))):?>
				<permalink><?=$article->permanent_url?></permalink>
			<?endif?>
			<?if(!empty(trim($article->article_reference))):?>
				<bibliography><?=htmlspecialchars($article->article_reference)?></bibliography>
			<?endif?>
				<?foreach($article->media as $media):?>
					<media>
						<url>https://pmc.qi-cms.com/media/_source/<?=$media->path?>/<?=$media->filename?></url>
					<?if(!empty(trim($media->title))):?>
						<title><?=htmlspecialchars($media->title)?></title>
					<?endif?>
					<?if(!empty(trim($media->caption))):?>
						<caption><?=htmlspecialchars($media->caption)?></caption>
					<?endif?>
					<?if(!empty(trim($media->credits))):?>
						<credits><?=htmlspecialchars($media->credits)?></credits>
					<?endif?>
					<?if(!empty(trim($media->copyright))):?>
						<copyright><?=htmlspecialchars($media->copyright)?></copyright>
					<?endif?>
					</media>
				<?endforeach?>
				<?foreach($article->chapters as $chapter):?>
					<chapter>
					<?if(!empty(trim($chapter->rank)) || $chapter->rank=='0'):?>
						<rank><?=$chapter->rank?></rank>
					<?endif?>
					<?if(!empty(trim($chapter->title))):?>
						<title><?=htmlspecialchars($chapter->title)?></title>
					<?endif?>
						<doi><?=str_replace("http://dx.doi.org/", "", rtrim(preference('bas_doi_prefix'), '/'))?>/<?=$issue->doi?>/<?=$article->doi?></doi>
						<?foreach($chapter->paragraphs as $paragraph):?>
							<paragraphs>
							<?if(!empty(trim($paragraph->rank))):?>
								<rank><?=$paragraph->rank?></rank>
							<?endif?>
							<?if(!empty(trim($paragraph->name))):?>
								<text><?=htmlspecialchars($paragraph->name)?></text>
							<?endif?>
								<doi><?=str_replace("http://dx.doi.org/", "", rtrim(preference('bas_doi_prefix'), '/'))?>/<?=$issue->doi?>/<?=$article->doi?>/<?=$paragraph->doi?></doi>
							</paragraphs>
						<?endforeach?>
						<?foreach($chapter->authors as $author):?>
							<author>
							<?if(!empty(trim($author->forename))):?>
								<forename><?=$author->forename?></forename>
							<?endif?>
							<?if(!empty(trim($author->surname))):?>
								<surname><?=$author->surname?></surname>
							<?endif?>
							<?if(!empty(trim($author->occupation))):?>
								<occupation><?=$author->occupation?></occupation>
							<?endif?>
							<?if(!empty(trim($author->short_description))):?>
								<bio><?=htmlspecialchars($author->short_description)?></bio>
							<?endif?>
							<?if(!empty(trim($author->affiliation))):?>
								<affiliation><?=$author->organisation?></affiliation>
							<?endif?>
							<?if(!empty(trim($author->orcid_id))):?>
								<orcid-id><?=$author->orcid_id?></orcid-id>
							<?endif?>
							</author>
						<?endforeach?>
						<figures>
						<?foreach($chapter->chart_links as $link):?>
							<external>
							<?if(!empty(trim($link->name))):?>
								<url><?=$link->name?></url>
							<?endif?>
							<?if(!empty(trim($link->title))):?>
								<title><?=htmlspecialchars($link->title)?></title>
							<?endif?>
							<?if(!empty(trim($link->caption))):?>
								<caption><?=htmlspecialchars($link->caption)?></caption>
							<?endif?>
							<?if(!empty(trim($link->credits))):?>
								<credits><?=htmlspecialchars($link->credits)?></credits>
							<?endif?>
							<?if(!empty(trim($link->copyright))):?>
								<copyright><?=htmlspecialchars($link->copyright)?></copyright>
							<?endif?>
							</external>
						<?endforeach?>
						<?foreach($chapter->zoom_links as $link):?>
							<IIIF>
							<?if(!empty(trim($link->name))):?>
								<url><?=$link->name?></url>
							<?endif?>
							<?if(!empty(trim($link->title))):?>
								<title><?=htmlspecialchars($link->title)?></title>
							<?endif?>
							<?if(!empty(trim($link->caption))):?>
								<caption><?=htmlspecialchars($link->caption)?></caption>
							<?endif?>
							<?if(!empty(trim($link->credits))):?>
								<credits><?=htmlspecialchars($link->credits)?></credits>
							<?endif?>
							<?if(!empty(trim($link->copyright))):?>
								<copyright><?=htmlspecialchars($link->copyright)?></copyright>
							<?endif?>
							</IIIF>
						<?endforeach?>
						<?foreach($chapter->media as $media):?>
							<media>
								<url>https://pmc.qi-cms.com/media/_source/<?=$media->path?>/<?=$media->filename?></url>
							<?if(!empty(trim($media->title))):?>	
								<title><?=htmlspecialchars($media->title)?></title>
							<?endif?>
							<?if(!empty(trim($media->caption))):?>
								<caption><?=htmlspecialchars($media->caption)?></caption>
							<?endif?>
							<?if(!empty(trim($media->credits))):?>
								<credits><?=htmlspecialchars($media->credits)?></credits>
							<?endif?>
							<?if(!empty(trim($media->copyright))):?>
								<copyright><?=htmlspecialchars($media->copyright)?></copyright>
							<?endif?>
							</media>
						<?endforeach?>				
						</figures>
					</chapter>
				<?endforeach?>
			</article>
		<?endforeach?>
	</issue>
</journal>
